animals = input("Enter a animal:")
animals_hair = input("Enter the animals hair:")
animal_trait = input("Enter a action about the animal:")
Color = input("Enter the color of animal:")
trait_with_color = input("Enter a boy part of the animal:")
trait_3 = input("enter another a trait of the animal:")
color_of_eyes = input("what color are the eyes of the animal:")
similar_animal = input("enter a similar animal:")
trait_4 = input("enter trait of the first animal:")
emotion =input("Enter in a emotion:\n")

print(f"Our {animals} have the softest {animals_hair}")
print(f"And the sweetest little {animal_trait},")
print(f"And such little {Color} {trait_with_color}")
print(f"With such cunning little {trait_3},")
print(f"And {color_of_eyes},just like the sky!\n")

print(f"Two are striped like{similar_animal},three")
print(f"Are as black as black can be,")
print(f"with their {trait_4},and are so{emotion},")
print(f"is it not a pity that ")
print(f"Each must grow into a {animals}?\n")
